name = "internship-radar"
main = "worker.js"
compatibility_date = "2026-06-19"
workers_dev = true
preview_urls = false

[observability]
enabled = true

[[kv_namespaces]]
binding = "SEEN"
id = "1ca154ac6e984d59b396205e282af2ea"

[triggers]
crons = []

[env.shard0]
name = "internship-radar-0"
workers_dev = false

[env.shard0.vars]
SHARD_INDEX = "0"

[[env.shard0.kv_namespaces]]
binding = "SEEN"
id = "1ca154ac6e984d59b396205e282af2ea"

[env.shard0.triggers]
crons = [ "*/5 * * * *" ]

[env.shard1]
name = "internship-radar-1"
workers_dev = false

[env.shard1.vars]
SHARD_INDEX = "1"

[[env.shard1.kv_namespaces]]
binding = "SEEN"
id = "1ca154ac6e984d59b396205e282af2ea"

[env.shard1.triggers]
crons = [ "*/5 * * * *" ]

[env.shard2]
name = "internship-radar-2"
workers_dev = false

[env.shard2.vars]
SHARD_INDEX = "2"

[[env.shard2.kv_namespaces]]
binding = "SEEN"
id = "1ca154ac6e984d59b396205e282af2ea"

[env.shard2.triggers]
crons = [ "*/5 * * * *" ]

[env.shard3]
name = "internship-radar-3"
workers_dev = false

[env.shard3.vars]
SHARD_INDEX = "3"

[[env.shard3.kv_namespaces]]
binding = "SEEN"
id = "1ca154ac6e984d59b396205e282af2ea"

[env.shard3.triggers]
crons = [ "*/5 * * * *" ]
